name = "Client Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "437b5092b901cca41ef513a7abb1e58e4301f81eb6b89f01adc38f92e5da31b9"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
