name = "Client Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99e5b322d8731949259908fa93ad66b3060e7714625c43f48c1ff3de9a7b7660"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
