name = "Client Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33e6c064072dc999e961f2c54865fa895e12976aea69acc7eea719dea53d84a0"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
