name = "Client Shit"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f9dc986045628c3f385cb189309ee205348dd624bfd6eecec5cd5df31b4cb04"

[versions]
fabric = "0.14.22"
minecraft = "1.20.1"
